"use client";

import { useEffect, useMemo, useState } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { CinematicAudioControl } from "@/components/audio/CinematicAudio";

const nodes = ["PEOPLE", "PROBLEM", "DESIGN", "BUILD", "IMPACT"] as const;
const tech = ["React", "Angular", "TypeScript", "Node.js", "Next.js", "Azure", "Terraform", "Dynamics 365", "Entra ID", "Firebase", "Supabase", "AI / RAG"];
const profileImage = "https://cdn.jsdelivr.net/gh/mdmoin7/portfolio@b4e402c3adbefe8714c71c5917299d758f86ee9a/assets/profile.webp";
function Arrow() { return <span aria-hidden="true">→</span>; }

export function ReimagineHome() {
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll();
  const [active, setActive] = useState(0);
  const [theme, setTheme] = useState<"dark" | "light">("light");
  const heroGlow = useTransform(scrollYProgress, [0, .22], [1, .2]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key >= "1" && e.key <= "5") setActive(Number(e.key) - 1); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const context = useMemo(() => ({ PEOPLE: "Developing the capability behind the technology.", PROBLEM: "Understanding the real constraint before choosing a tool.", DESIGN: "Turning complexity into systems people can reason about.", BUILD: "Shipping production-minded software, not presentationware.", IMPACT: "Leaving behind usable systems, capability, and momentum." }), []);
  return <div className={`reimagine ${theme === "light" ? "is-light" : "is-dark"}`}>
    <aside className="spatial-nav" aria-label="Portfolio navigation"><div className="spatial-brand">M<span>/</span>M</div><div className="spatial-line" aria-hidden="true" /><nav>{["THESIS","SYSTEM","CAPABILITY","TECHNOLOGY","WORK","TRAINING","LABS","ABOUT","CONTACT"].map(item => <a key={item} href={`#${item.toLowerCase()}`} className="spatial-link"><span>{item}</span></a>)}</nav><button className="mode-toggle" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label="Toggle visual environment"><span aria-hidden="true">{theme === "dark" ? "◐" : "◑"}</span></button></aside>
    <main>
      <section className="hero-v2" id="thesis"><div className="hero-atmosphere" aria-hidden="true" /><motion.div className="hero-orbit" style={reduce ? undefined : { opacity: heroGlow }} aria-hidden="true" /><div className="hero-grid" aria-hidden="true" /><div className="hero-meta mono"><span>INDEPENDENT SOFTWARE ENGINEERING CONSULTANT</span><span>·</span><span>CORPORATE TECHNOLOGY TRAINER</span></div><div className="hero-copy"><p className="eyebrow mono">ENGINEERING × PEOPLE × AI</p><h1>Build People.<br />Solve Problems.<br /><em>Innovate.</em></h1><p className="hero-lede">I help organizations design, build and scale modern software systems while enabling teams through practical, hands-on training.</p><div className="hero-actions"><a href="#work" className="primary-action">Work with me <Arrow /></a><a href="#training" className="secondary-action">Explore training <Arrow /></a></div><div className="hero-stats"><div><strong>15K+</strong><span>Engineers trained</span></div><div><strong>350+</strong><span>Training sessions</span></div><div><strong>14+</strong><span>Years in production</span></div></div></div><div className="hero-portrait-wrap"><div className="hero-portrait-halo" aria-hidden="true" /><img className="hero-portrait" src={profileImage} alt="Mohammad Moin" /><div className="hero-callout"><span>“</span><p>Technology becomes capability when people are empowered.</p><small>MOHAMMAD MOIN</small></div><div className="hero-side-label mono">MODERN TECHNOLOGY<br />REAL IMPACT</div></div><div className="hero-scroll mono">SCROLL TO EXPLORE <span>↓</span></div></section>
      <section className="system-section" id="system"><div className="section-marker mono">01 / APPROACH</div><div className="system-intro"><p className="eyebrow mono">MY APPROACH</p><h2>From people<br />to real <em>impact.</em></h2><p className="section-lede">A practical, end-to-end approach to help teams and organizations turn complex problems into scalable, real-world solutions.</p></div><div className="system-map" role="group" aria-label="People to impact system map"><div className="system-track" aria-hidden="true" />{nodes.map((node,i)=><button key={node} className={`system-node ${active===i?"active":""}`} onClick={()=>setActive(i)} aria-pressed={active===i}><span className="node-index mono">0{i+1}</span><span className="node-icon" aria-hidden="true">{["◉","◎","◇","⌘","↗"][i]}</span><span className="node-name">{node}</span><span className="node-description">{["Understand teams, challenges and goals.","Define the right problem to solve.","Architect practical and scalable solutions.","Engineer, implement and iterate.","Deliver measurable outcomes."][i]}</span></button>)}</div><a className="section-link" href="#capability">Discover my approach <Arrow /></a></section>
      <section className="capability-section" id="capability"><div className="section-marker mono">02 / CAPABILITY</div><div className="capability-copy"><p className="eyebrow mono">HOW I HELP</p><h2>From capability<br /><em>to impact.</em></h2><p className="section-lede">I bridge the gap between advanced technology and real-world outcomes through consulting, development and hands-on training.</p><a className="section-link" href="#contact">Explore all services <Arrow /></a></div><div className="capability-grid"><article><span className="card-icon">◎</span><h3>Corporate Training</h3><p>Practical, role-based training for modern technology teams.</p><a href="#training">View programs <Arrow /></a></article><article><span className="card-icon">⌘</span><h3>Consulting & Architecture</h3><p>Design and build scalable systems for real business problems.</p><a href="#work">Learn more <Arrow /></a></article><article><span className="card-icon">◌</span><h3>AI / RAG Solutions</h3><p>Build intelligent systems with LLMs, embeddings and real data.</p><a href="#labs">Explore AI <Arrow /></a></article><article><span className="card-icon">▦</span><h3>Real-world Projects</h3><p>From concept to production with measurable impact.</p><a href="#work">View projects <Arrow /></a></article></div></section>
      <section className="technology-section" id="technology"><div className="section-marker mono">03 / TECHNOLOGY</div><div className="tech-copy"><p className="eyebrow mono">TECHNOLOGY LANDSCAPE</p><h2>Systems I<br /><em>work with.</em></h2><p className="tech-lede">Modern tools. Real solutions. Enterprise ready.</p></div><div className="constellation" aria-label="Technology constellation">{tech.map((item,i)=><button key={item} className={`tech-node t${i+1}`} onClick={()=>setActive(i%5)}>{item}</button>)}<div className="constellation-core">ENGINEERING<br /><small>× PEOPLE × AI</small></div></div><div className="tech-footer mono">AND MORE <Arrow /></div></section>
      <section className="work-section" id="work"><div className="section-marker mono">04 / WORK</div><div className="work-head"><div><p className="eyebrow mono">SELECTED SYSTEMS</p><h2>Problems made <em>concrete.</em></h2></div><p>Case-study thinking over screenshot galleries: problem → system → engineering → outcome.</p></div><div className="work-grid"><article className="work-card work-featured"><span className="mono">AQUATRACK / DATA → DECISIONS</span><h3>Water consumption into an operational system.</h3><p>Readings → analytics → billing → expenses → reporting → alerts.</p><div className="work-tags">React · TypeScript · Firebase · Analytics</div><a href="#contact">Discuss the system <Arrow /></a></article><article className="work-card"><span className="mono">INCOME TRACKER / STATE → TRUST</span><h3>Authentication with lifecycle thinking.</h3><p>Auth → token lifecycle → TTL → refresh → data.</p><div className="work-tags">React · TypeScript · Supabase</div></article><article className="work-card"><span className="mono">ENTERPRISE REACT / IDENTITY → EXPERIENCE</span><h3>Role-aware enterprise interfaces.</h3><p>User → auth → role-aware UX → React → Dataverse.</p><div className="work-tags">React · Entra ID · MSAL · Dataverse</div></article></div></section>
      <section className="training-section" id="training"><div className="section-marker mono">05 / TRAINING</div><div className="training-layout"><div><p className="eyebrow mono">BUILD PEOPLE</p><h2>Training is capability<br /><em>engineering.</em></h2></div><div className="training-flow"><div>ASSESS</div><span>→</span><div>FOUNDATION</div><span>→</span><div>APPLIED</div><span>→</span><div>PRODUCTION</div><span>→</span><div>OWNERSHIP</div></div><p className="training-note">15K+ engineers trained · 350+ sessions delivered · 14+ years in production</p><a className="primary-action" href="mailto:mohammad.nicoll@gmail.com?subject=Training%20engagement">Discuss a training program <Arrow /></a></div></section>
      <section className="labs-section" id="labs"><div className="section-marker mono">06 / LABS</div><div className="labs-layout"><div><p className="eyebrow mono">AI / RAG / ENGINEERING</p><h2>Experiment, then<br /><em>make it useful.</em></h2></div><div className="lab-list"><div><span className="mono">01</span><strong>AI / RAG systems</strong><p>LLM applications, embeddings, retrieval, vector search, and practical AI workflows.</p></div><div><span className="mono">02</span><strong>Frontend architecture</strong><p>React, Angular, state, micro frontends, and design systems.</p></div><div><span className="mono">03</span><strong>Cloud / infrastructure</strong><p>Azure, Terraform, CI/CD, and systems that can be operated.</p></div></div></div></section>
      <section className="about-v2" id="about"><div className="section-marker mono">07 / AUTHOR</div><div className="author-layout"><div className="author-photo"><img src={profileImage} alt="Portrait of Mohammad Moin, independent technology consultant and corporate technology trainer" /></div><div><p className="eyebrow mono">MOHAMMAD MOIN</p><h2>Build the system.<br />Develop the <em>capability.</em></h2><p>I work at the intersection of engineering, people, and practical delivery. I care about clear systems, useful abstractions, production reality, and helping teams move from knowing to doing.</p><p>The measure is simple: the solution works, the people can operate it, and the organization can keep moving.</p></div></div></section>
      <section className="contact-v2" id="contact"><div className="section-marker mono">08 / CONTACT</div><div className="contact-center"><p className="eyebrow mono">INDEPENDENT CONSULTANT · CORPORATE TECHNOLOGY TRAINER</p><h2>Have a problem worth<br /><em>building around?</em></h2><p>Consulting, corporate training, engineering work, or a conversation about what comes next.</p><a className="contact-link" href="mailto:mohammad.nicoll@gmail.com">mohammad.nicoll@gmail.com <Arrow /></a><div className="contact-meta mono"><span>BUILD PEOPLE</span><span>SOLVE PROBLEMS</span><span>INNOVATE</span></div></div></section>
    </main><footer className="footer-v2"><span>MOHAMMAD MOIN</span><span>INDEPENDENT CONSULTANT · CORPORATE TECHNOLOGY TRAINER</span><span>© 2026</span></footer><CinematicAudioControl /></div>;
}
